my_string = input('Напиши здесь что нибудь: ')
number_of_characters = len(my_string)
print('Количество символов: ', number_of_characters)
print(my_string .upper())
print(my_string .lower())
print(my_string .replace(' ', '#'))
print(my_string [0])
print(my_string [-1])